### ISSUE TITLE
person/place tag longer than one line miss @continued

### ISSUE THREAD

**Issue by thodel** [dariok/page2tei#10]
Information/connection of tags (esp. places and persons) spanning more than one line get lost.
In pagexml: continued=true.
@continued in TEI only gets added to <date>-tag.

Best case would of course be to only have one tag per entity.

**Comment by dariok** [comment]
@thodel Sorry for the late reply, too much going on at the moment.

The question is how to export this. This case is often handled differently by projects. Some use `lb/@break`, others rely on a `w` surrounding both `text()` nodes and the `lb` etc.

- Should we export as `<rs>begin-<lb break="no"/>ning</rs>`?
- Can we rely on `@continued` being correct or do we need additional checks?

**Comment by thodel** [comment]
@dariok thanks for the reply and no worries.
- Sounds reasonable to me: `<rs>begin-<lb break="no"/>ning</rs>` (for our project we replace the break (`-`) with `@break="no"` in a separated script (in post-processing).
- I would rely on tagging of pageXML by user in Transkribus (based on `@continued`), I don't see a way, how to carry out more checks. To check for same tags at the starting of a line seems way too risky.

**Comment by dariok** [comment]
@thodel I finally managed to get back to this and it is resolved. Some testing is still needed to make sure whitespace around `lb` is still handled correctly.

**Comment by thodel** [comment]
Thx so much! Looking forward to check it out.
