### ISSUE TITLE
Image names with space

### ISSUE THREAD

**Issue by hackmanschorsch** [dariok/page2tei#4]
If we take the image name as identifier and it contains a space - like in this example
`<pb facs='#facs_1' xml:id='JRL MS_551_1_p01.jpg' n='1'/>`
we get an invalid TEI XML. Should we use an artificial identifier instead, e.g. IMG_1, IMG_2,...?

**Comment by dariok** [comment]
I think that a generated ID would be best here. The name of the image is present in the corresponding `tei:graphic` element so repeating it here is not necessary. I'd say that `img_0001`... would be best here.
If someone wishes to have the file name here, this can be easily done in a later step. In thta case, it should be URL encoded.
